// <auto-generated />
using ApiFilmes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiFilmes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211207080300_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiFilmes.Data.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Ano")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Duracao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FaixaEtaria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Filmes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = "2069",
                            Duracao = "2 horas",
                            FaixaEtaria = "+18",
                            Genero = "Ação",
                            Titulo = "A volta dos que não foram"
                        },
                        new
                        {
                            Id = 2,
                            Ano = "2069",
                            Duracao = "2 horas",
                            FaixaEtaria = "+18",
                            Genero = "Ação",
                            Titulo = "As tranças do rei careca"
                        },
                        new
                        {
                            Id = 3,
                            Ano = "2069",
                            Duracao = "2 horas",
                            FaixaEtaria = "+18",
                            Genero = "Ação",
                            Titulo = "Poeira em alto mar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
